### ISSUE TITLE
Basic config in README fails to build/deploy

### ISSUE THREAD

**Issue by ericmarcos** [serverless-components/chat-app#1]
The `serverless` command fails after creating a new project with the chat-app README serverless.yml config:
```
myChatApp:
  component: '@serverless/chat-app'
  inputs: # all inputs are optional :)
    colorBackground: white
    colorInputText: black
    logoUrl: null
```

Error output:
```
  Error: Failed building website via "npm run build" due to the following error: "npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ChatApp@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ChatApp@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eric/.npm/_logs/2020-03-28T18_27_21_138Z-debug.log
"
    at Website.default (/Users/eric/.serverless/components/registry/npm/@serverless/chat-app@1.0.1/node_modules/@serverless/website/serverless.js:86:15)

  17s › myChatApp › Error: Failed building website via "npm run build" due to the following error: "npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ChatApp@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ChatApp@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eric/.npm/_logs/2020-03-28T18_27_21_138Z-debug.log
```
